@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 06 15:36:54 +0800 2024
REM SW Build 4081461 on Thu Dec 14 12:24:51 MST 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim cpuTest_behav -key {Behavioral:sim_1:Functional:cpuTest} -tclbatch cpuTest.tcl -view C:/Users/Louie/Desktop/Files Y3 Term 3/LBYCPD3/project_fpu/cpuTest_behav.wcfg -log simulate.log"
call xsim  cpuTest_behav -key {Behavioral:sim_1:Functional:cpuTest} -tclbatch cpuTest.tcl -view C:/Users/Louie/Desktop/Files Y3 Term 3/LBYCPD3/project_fpu/cpuTest_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
